---
title: "R Notebook"
output: html_notebook
---
```{r}
#install.packages("tidyverse")
```


```{r}
library(readr)
library(tidyverse)
```


```{r}
mm<- read_table2("/Volumes/5ive3rds/CSULB/Classes/510/Data/Data Sets KN/KutnerData/Chapter  1 Data Sets/CH01PR27.txt", 
    col_names = FALSE)

ym<-mm$X1

names(mm)<-c("ym","xm")
fit<-lm(ym~xm,data = mm)
```

EXERCISE 1.27a
```{r}
summary(fit)
```


```{r}
#Scatterplot
plot(xm,ym,xlab="Age",ylab="Muscle Mass")
abline(a=fit$coefficients[1],b=fit$coefficients[2]) 
```


```{r}
ggplot(mm,aes(x=xm,y=ym)) +
   geom_point() +
   stat_smooth(method='lm') +
   xlab("Age") +
   ylab("Muscle Mass")
```

EXERCISE 8.4
To run quadratic predictors, we must first center the $x_i$'s:
```{r}
xms<-scale(mm$xm,scale=F)
xms2<-xms^2
mms<-cbind(mm,xms,xms2)
head(mms)
```

EXERCISE 8.4abe
```{r}
fit2<-lm(ym~xms+xms2,data = mms)
summary(fit2)
```

```{r}
ggplot(mm,aes(x=xm,y=ym)) +
   geom_point() +
   stat_smooth(method='lm',formula=y~poly(x,2),size=1) +
   xlab("Age") +
   ylab("Muscle Mass")
```

EXERCISE 8.4c
```{r}
predict(fit2,data.frame(xms=(48-mean(mm$xm)),xms2=(48-mean(mm$xm))^2),interval="confidence",level=0.95)

predict(fit2,data.frame(xms=(48-mean(mm$xm)),xms2=(48-mean(mm$xm))^2),interval="predict",level=0.95)
```

EXERCISE 8.4fg
```{r}
xm2<-mm$xm^2
mmss<-cbind(mms,xm2)
head(mmss)
``` 
```{r}
summary(lm(ym~xm+xm2,data=mmss))
```

Check $b_1'$ (see pg 299)
```{r}
fit2$coefficients[2]-2*mean(mm$xm)*fit2$coefficients[3]
```


Part g: Correlation reduction
```{r}
#Pre-centered
cor(mmss$xm,mmss$xm2)

#Centered
cor(mmss$xms,mmss$xms2)


```


```{r}
avPlots(fit2,ask=T)
```

